/**
 * Asset key constants for the game.
 * These keys are used to reference assets loaded by Phaser's loader.
 * Legacy assets are served from /assets/archive/ and are organized by type and creator.
 */

export const EXTERNAL_LINKS_ASSET_KEYS = {
  GITHUB_BANNER: 'GITHUB_BANNER',
  LEARN_MORE_BACKGROUND: 'LEARN_MORE_BACKGROUND',
  YOUTUBE_BUTTON: 'YOUTUBE_BUTTON',
  YOUTUBE_THUMB_NAIL: 'YOUTUBE_THUMB_NAIL',
} as const;

export const BATTLE_BACKGROUND_ASSET_KEYS = {
  FOREST: 'FOREST',
} as const;

export const MONSTER_ASSET_KEYS = {
  IGUANIGNITE: 'IGUANIGNITE',
  CARNODUSK: 'CARNODUSK',
  IGNIVOLT: 'IGNIVOLT',
  AQUAVALOR: 'AQUAVALOR',
  FROSTSABER: 'FROSTSABER',
} as const;

export const BATTLE_ASSET_KEYS = {
  HEALTH_BAR_BACKGROUND: 'HEALTH_BAR_BACKGROUND',
  BALL_THUMBNAIL: 'BALL_THUMBNAIL',
  DAMAGED_BALL: 'DAMAGED_BALL',
} as const;

export const HEALTH_BAR_ASSET_KEYS = {
  LEFT_CAP: 'LEFT_CAP',
  MIDDLE: 'MIDDLE',
  RIGHT_CAP: 'RIGHT_CAP',
  LEFT_CAP_SHADOW: 'LEFT_CAP_SHADOW',
  MIDDLE_SHADOW: 'MIDDLE_SHADOW',
  RIGHT_CAP_SHADOW: 'RIGHT_CAP_SHADOW',
} as const;

export const EXP_BAR_ASSET_KEYS = {
  EXP_LEFT_CAP: 'EXP_LEFT_CAP',
  EXP_MIDDLE: 'EXP_MIDDLE',
  EXP_RIGHT_CAP: 'EXP_RIGHT_CAP',
} as const;

export const UI_ASSET_KEYS = {
  CURSOR: 'CURSOR',
  CURSOR_WHITE: 'CURSOR_WHITE',
  MENU_BACKGROUND: 'MENU_BACKGROUND',
  MENU_BACKGROUND_GREEN: 'MENU_BACKGROUND_GREEN',
  MENU_BACKGROUND_PURPLE: 'MENU_BACKGROUND_PURPLE',
  BLUE_BUTTON: 'BLUE_BUTTON',
  BLUE_BUTTON_SELECTED: 'BLUE_BUTTON_SELECTED',
} as const;

export const DATA_ASSET_KEYS = {
  ATTACKS: 'ATTACKS',
  ANIMATIONS: 'ANIMATIONS',
  ITEMS: 'ITEMS',
  MONSTERS: 'MONSTERS',
  ENCOUNTERS: 'ENCOUNTERS',
  NPCS: 'NPCS',
  EVENTS: 'EVENTS',
  SIGNS: 'SIGNS',
} as const;

export const ATTACK_ASSET_KEYS = {
  ICE_SHARD: 'ICE_SHARD',
  ICE_SHARD_START: 'ICE_SHARD_START',
  SLASH: 'SLASH',
} as const;

export const WORLD_ASSET_KEYS = {
  MAIN_1_BACKGROUND: 'MAIN_1_BACKGROUND',
  MAIN_1_FOREGROUND: 'MAIN_1_FOREGROUND',
  MAIN_1_LEVEL: 'MAIN_1_LEVEL',
  WORLD_COLLISION: 'WORLD_COLLISION',
  WORLD_ENCOUNTER_ZONE: 'WORLD_ENCOUNTER_ZONE',
  BEACH: 'BEACH',
  GRASS: 'GRASS',
  FOREST_1_BACKGROUND: 'FOREST_1_BACKGROUND',
  FOREST_1_FOREGROUND: 'FOREST_1_FOREGROUND',
  FOREST_1_LEVEL: 'FOREST_1_LEVEL',
} as const;

export const BUILDING_ASSET_KEYS = {
  BUILDING_1_BACKGROUND: 'BUILDING_1_BACKGROUND',
  BUILDING_1_FOREGROUND: 'BUILDING_1_FOREGROUND',
  BUILDING_1_LEVEL: 'BUILDING_1_LEVEL',
  BUILDING_2_BACKGROUND: 'BUILDING_2_BACKGROUND',
  BUILDING_2_FOREGROUND: 'BUILDING_2_FOREGROUND',
  BUILDING_2_LEVEL: 'BUILDING_2_LEVEL',
  BUILDING_3_BACKGROUND: 'BUILDING_3_BACKGROUND',
  BUILDING_3_FOREGROUND: 'BUILDING_3_FOREGROUND',
  BUILDING_3_LEVEL: 'BUILDING_3_LEVEL',
} as const;

export const CHARACTER_ASSET_KEYS = {
  PLAYER: 'PLAYER',
  NPC: 'NPC',
} as const;

export const TITLE_ASSET_KEYS = {
  BACKGROUND: 'BACKGROUND',
  TITLE: 'TITLE',
  PANEL: 'PANEL',
} as const;

export const MONSTER_PARTY_ASSET_KEYS = {
  PARTY_BACKGROUND: 'PARTY_BACKGROUND',
  MONSTER_DETAILS_BACKGROUND: 'MONSTER_DETAILS_BACKGROUND',
} as const;

export const INVENTORY_ASSET_KEYS = {
  INVENTORY_BACKGROUND: 'INVENTORY_BACKGROUND',
  INVENTORY_BAG: 'INVENTORY_BAG',
} as const;

export const AUDIO_ASSET_KEYS = {
  TITLE: 'TITLE',
  BATTLE: 'BATTLE',
  MAIN: 'MAIN',
  FLEE: 'FLEE',
  GRASS: 'GRASS',
  CLAW: 'CLAW',
  ICE: 'ICE',
} as const;

/**
 * Type definitions for asset keys
 */
export type ExternalLinksAssetKey = typeof EXTERNAL_LINKS_ASSET_KEYS[keyof typeof EXTERNAL_LINKS_ASSET_KEYS];
export type BattleBackgroundAssetKey = typeof BATTLE_BACKGROUND_ASSET_KEYS[keyof typeof BATTLE_BACKGROUND_ASSET_KEYS];
export type MonsterAssetKey = typeof MONSTER_ASSET_KEYS[keyof typeof MONSTER_ASSET_KEYS];
export type BattleAssetKey = typeof BATTLE_ASSET_KEYS[keyof typeof BATTLE_ASSET_KEYS];
export type HealthBarAssetKey = typeof HEALTH_BAR_ASSET_KEYS[keyof typeof HEALTH_BAR_ASSET_KEYS];
export type ExpBarAssetKey = typeof EXP_BAR_ASSET_KEYS[keyof typeof EXP_BAR_ASSET_KEYS];
export type UIAssetKey = typeof UI_ASSET_KEYS[keyof typeof UI_ASSET_KEYS];
export type DataAssetKey = typeof DATA_ASSET_KEYS[keyof typeof DATA_ASSET_KEYS];
export type AttackAssetKey = typeof ATTACK_ASSET_KEYS[keyof typeof ATTACK_ASSET_KEYS];
export type WorldAssetKey = typeof WORLD_ASSET_KEYS[keyof typeof WORLD_ASSET_KEYS];
export type BuildingAssetKey = typeof BUILDING_ASSET_KEYS[keyof typeof BUILDING_ASSET_KEYS];
export type CharacterAssetKey = typeof CHARACTER_ASSET_KEYS[keyof typeof CHARACTER_ASSET_KEYS];
export type TitleAssetKey = typeof TITLE_ASSET_KEYS[keyof typeof TITLE_ASSET_KEYS];
export type MonsterPartyAssetKey = typeof MONSTER_PARTY_ASSET_KEYS[keyof typeof MONSTER_PARTY_ASSET_KEYS];
export type InventoryAssetKey = typeof INVENTORY_ASSET_KEYS[keyof typeof INVENTORY_ASSET_KEYS];
export type AudioAssetKey = typeof AUDIO_ASSET_KEYS[keyof typeof AUDIO_ASSET_KEYS];
