/**
 * Data key enums - Provide strongly typed identifiers for structured JSON assets
 */
export enum CoreDataKeys {
  AREAS = 'AREAS',
  AREAS_SCHEMA = 'AREAS_SCHEMA',
  CRITTERS = 'CRITTERS',
  CRITTERS_SCHEMA = 'CRITTERS_SCHEMA',
  ITEMS = 'ITEMS',
  ITEMS_SCHEMA = 'ITEMS_SCHEMA',
  MOVES = 'MOVES',
  MOVES_SCHEMA = 'MOVES_SCHEMA',
  TYPES = 'TYPES',
  TYPES_SCHEMA = 'TYPES_SCHEMA',
  LEGACY_CRITTER_INDEX = 'LEGACY_CRITTER_INDEX',
  LEGACY_ENCOUNTER_INDEX = 'LEGACY_ENCOUNTER_INDEX',
  LEGACY_EVENT_INDEX = 'LEGACY_EVENT_INDEX',
  LEGACY_ID_MAPPINGS = 'LEGACY_ID_MAPPINGS',
  LEGACY_ITEM_INDEX = 'LEGACY_ITEM_INDEX',
  LEGACY_MOVE_INDEX = 'LEGACY_MOVE_INDEX',
  LEGACY_NPC_INDEX = 'LEGACY_NPC_INDEX',
  LEGACY_SIGN_INDEX = 'LEGACY_SIGN_INDEX'
}

export enum LegacyDataKeys {
  LEGACY_ATTACKS = 'LEGACY_ATTACKS',
  LEGACY_ANIMATIONS = 'LEGACY_ANIMATIONS',
  LEGACY_ITEMS = 'LEGACY_ITEMS',
  LEGACY_MONSTERS = 'LEGACY_MONSTERS',
  LEGACY_ENCOUNTERS = 'LEGACY_ENCOUNTERS',
  LEGACY_NPCS = 'LEGACY_NPCS',
  LEGACY_EVENTS = 'LEGACY_EVENTS',
  LEGACY_SIGNS = 'LEGACY_SIGNS',
  BUILDING_1 = 'BUILDING_1',
  BUILDING_2 = 'BUILDING_2',
  BUILDING_3 = 'BUILDING_3',
  FOREST_1 = 'FOREST_1',
  MAIN_1 = 'MAIN_1',
  LEVEL = 'LEVEL',
  LEVEL_OLD = 'LEVEL_OLD'
}

export type DataKey = CoreDataKeys | LegacyDataKeys;
