/**
 * Data key enums - Provide strongly typed identifiers for structured JSON assets
 */
export enum CoreDataKeys {
  AREAS = 'AREAS',
  AREAS_SCHEMA = 'AREAS_SCHEMA',
  CRITTERS = 'CRITTERS',
  CRITTERS_SCHEMA = 'CRITTERS_SCHEMA',
  ITEMS = 'CORE_ITEMS',
  ITEMS_SCHEMA = 'CORE_ITEMS_SCHEMA',
  MOVES = 'MOVES',
  MOVES_SCHEMA = 'MOVES_SCHEMA',
  TYPES = 'TYPES',
  TYPES_SCHEMA = 'TYPES_SCHEMA',
  LEGACY_CRITTER_INDEX = 'LEGACY_CRITTER_INDEX',
  LEGACY_ENCOUNTER_INDEX = 'LEGACY_ENCOUNTER_INDEX',
  LEGACY_EVENT_INDEX = 'LEGACY_EVENT_INDEX',
  LEGACY_ID_MAPPINGS = 'LEGACY_ID_MAPPINGS',
  LEGACY_ITEM_INDEX = 'LEGACY_ITEM_INDEX',
  LEGACY_MOVE_INDEX = 'LEGACY_MOVE_INDEX',
  LEGACY_NPC_INDEX = 'LEGACY_NPC_INDEX',
  LEGACY_SIGN_INDEX = 'LEGACY_SIGN_INDEX'
}

export enum LegacyDataKeys {
  ATTACKS = 'ATTACKS',
  ANIMATIONS = 'ANIMATIONS',
  ITEMS = 'ITEMS',
  MONSTERS = 'MONSTERS',
  ENCOUNTERS = 'ENCOUNTERS',
  NPCS = 'NPCS',
  EVENTS = 'EVENTS',
  SIGNS = 'SIGNS',
  BUILDING_1 = 'BUILDING_1',
  BUILDING_2 = 'BUILDING_2',
  BUILDING_3 = 'BUILDING_3',
  FOREST_1 = 'FOREST_1',
  MAIN_1 = 'MAIN_1',
  LEVEL = 'LEVEL',
  LEVEL_OLD = 'LEVEL_OLD'
}

export type DataKey = CoreDataKeys | LegacyDataKeys;
