/**
 * Texture Keys enum - Mirrors archive/src/assets/asset-keys.js (visual assets)
 * Centralized constants for all texture assets to ensure consistency
 */
export enum TextureKeys {
  // External Links
  GITHUB_BANNER = 'GITHUB_BANNER',
  LEARN_MORE_BACKGROUND = 'LEARN_MORE_BACKGROUND',
  YOUTUBE_BUTTON = 'YOUTUBE_BUTTON',
  YOUTUBE_THUMB_NAIL = 'YOUTUBE_THUMB_NAIL',

  // Battle Backgrounds
  BATTLE_FOREST = 'FOREST',

  // Monsters
  MONSTER_IGUANIGNITE = 'IGUANIGNITE',
  MONSTER_CARNODUSK = 'CARNODUSK',
  MONSTER_IGNIVOLT = 'IGNIVOLT',
  MONSTER_AQUAVALOR = 'AQUAVALOR',
  MONSTER_FROSTSABER = 'FROSTSABER',

  // Battle UI
  HEALTH_BAR_BACKGROUND = 'HEALTH_BAR_BACKGROUND',
  BALL_THUMBNAIL = 'BALL_THUMBNAIL',
  DAMAGED_BALL = 'DAMAGED_BALL',

  // Health Bar Components
  HEALTH_LEFT_CAP = 'LEFT_CAP',
  HEALTH_MIDDLE = 'MIDDLE',
  HEALTH_RIGHT_CAP = 'RIGHT_CAP',
  HEALTH_LEFT_CAP_SHADOW = 'LEFT_CAP_SHADOW',
  HEALTH_MIDDLE_SHADOW = 'MIDDLE_SHADOW',
  HEALTH_RIGHT_CAP_SHADOW = 'RIGHT_CAP_SHADOW',

  // Experience Bar Components
  EXP_LEFT_CAP = 'EXP_LEFT_CAP',
  EXP_MIDDLE = 'EXP_MIDDLE',
  EXP_RIGHT_CAP = 'EXP_RIGHT_CAP',

  // UI Elements
  CURSOR = 'CURSOR',
  CURSOR_WHITE = 'CURSOR_WHITE',
  MENU_BACKGROUND = 'MENU_BACKGROUND',
  MENU_BACKGROUND_GREEN = 'MENU_BACKGROUND_GREEN',
  MENU_BACKGROUND_PURPLE = 'MENU_BACKGROUND_PURPLE',
  BLUE_BUTTON = 'BLUE_BUTTON',
  BLUE_BUTTON_SELECTED = 'BLUE_BUTTON_SELECTED',

  // Attack Effects
  ATTACK_ICE_SHARD = 'ICE_SHARD',
  ATTACK_ICE_SHARD_START = 'ICE_SHARD_START',
  ATTACK_SLASH = 'SLASH',

  // World Assets
  WORLD_MAIN_1_BACKGROUND = 'MAIN_1_BACKGROUND',
  WORLD_MAIN_1_FOREGROUND = 'MAIN_1_FOREGROUND',
  WORLD_MAIN_1_LEVEL = 'MAIN_1_LEVEL',
  WORLD_COLLISION = 'WORLD_COLLISION',
  WORLD_ENCOUNTER_ZONE = 'WORLD_ENCOUNTER_ZONE',
  WORLD_BEACH = 'BEACH',
  WORLD_GRASS = 'GRASS',
  WORLD_FOREST_1_BACKGROUND = 'FOREST_1_BACKGROUND',
  WORLD_FOREST_1_FOREGROUND = 'FOREST_1_FOREGROUND',
  WORLD_FOREST_1_LEVEL = 'FOREST_1_LEVEL',
  WORLD = 'WORLD', // General world assets

  // Building Assets
  BUILDING_1_BACKGROUND = 'BUILDING_1_BACKGROUND',
  BUILDING_1_FOREGROUND = 'BUILDING_1_FOREGROUND',
  BUILDING_1_LEVEL = 'BUILDING_1_LEVEL',
  BUILDING_2_BACKGROUND = 'BUILDING_2_BACKGROUND',
  BUILDING_2_FOREGROUND = 'BUILDING_2_FOREGROUND',
  BUILDING_2_LEVEL = 'BUILDING_2_LEVEL',
  BUILDING_3_BACKGROUND = 'BUILDING_3_BACKGROUND',
  BUILDING_3_FOREGROUND = 'BUILDING_3_FOREGROUND',
  BUILDING_3_LEVEL = 'BUILDING_3_LEVEL',

  // Characters
  CHARACTER_PLAYER = 'PLAYER',
  CHARACTER_NPC = 'NPC',

  // Title Screen
  TITLE_BACKGROUND = 'BACKGROUND',
  TITLE_LOGO = 'TITLE',
  TITLE_PANEL = 'PANEL',

  // Monster Party
  PARTY_BACKGROUND = 'PARTY_BACKGROUND',
  MONSTER_DETAILS_BACKGROUND = 'MONSTER_DETAILS_BACKGROUND',

  // Inventory
  INVENTORY_BACKGROUND = 'INVENTORY_BACKGROUND',
  INVENTORY_BAG = 'INVENTORY_BAG'
}